<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_About</name>
   <tag></tag>
   <elementGuidId>8331b509-a71a-4a83-abb3-fa2e2bbe0121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.et_pb_menu_page_id-217456.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-has-children.menu-item-217539 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-home-page-menu']/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79d7e46f-53b5-4ad2-aa2e-cdfb4af5a326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ultimateqa.com/about/</value>
      <webElementGuid>6ec3e14b-d55a-4103-825d-253a4d166be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About</value>
      <webElementGuid>2e4d8937-cd51-4bb8-8c8f-f71a39580124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-home-page-menu&quot;)/li[@class=&quot;et_pb_menu_page_id-217456 menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-217539&quot;]/a[1]</value>
      <webElementGuid>04891dbd-affd-44d2-a60f-3b61d69ab7e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-home-page-menu']/li[6]/a</value>
      <webElementGuid>7aa3344d-55ce-471a-b029-32ce25ed8793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'About')]</value>
      <webElementGuid>95bf47a5-eedc-42eb-8fc4-5d2fe3c3dd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/following::a[1]</value>
      <webElementGuid>ed2da3e1-4715-4e15-9662-2f9ddc1cff77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success Stories'])[1]/following::a[2]</value>
      <webElementGuid>341e60cd-9d5e-4249-bfd8-a40e51fbd358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[1]</value>
      <webElementGuid>eb539ff2-c4d3-4b59-aa93-46bd7bff3703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LinkedIn'])[1]/preceding::a[2]</value>
      <webElementGuid>657b82c8-3e33-4547-bd97-626dab8c1d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='About']/parent::*</value>
      <webElementGuid>42461d5b-8e0e-47bb-8a65-7bdb37c9c951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ultimateqa.com/about/')]</value>
      <webElementGuid>a80ca73f-de31-4e74-9e4a-25a454435ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>60fcd93e-f20d-47c2-b3ff-3c2c60d8c9a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ultimateqa.com/about/' and (text() = 'About' or . = 'About')]</value>
      <webElementGuid>55963b4a-79c0-49de-bd57-0fb3720bf1cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
