<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Desktop</name>
   <tag></tag>
   <elementGuidId>a2ef911b-cc3d-4352-8e6d-81cd929bce94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_T53129E6C012_Col00']/nav/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a03def63-b335-4cae-a78b-589ddca9baa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#desktop</value>
      <webElementGuid>a71cf457-34a9-4c0f-bcba-3f8c7c31be43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavAlt-anchor u-b0</value>
      <webElementGuid>253e41f6-e6c0-4581-bd21-388c8963c806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Desktop content</value>
      <webElementGuid>6be4b810-fcea-431e-bef1-8b1f1f4150cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desktop</value>
      <webElementGuid>a0c69f4b-0330-4c31-9cf3-c9842d547ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_T53129E6C012_Col00&quot;)/nav[@class=&quot;NavAlt NavAlt--blue u-bn u-tal u-b0&quot;]/div[@class=&quot;container&quot;]/div[2]/a[@class=&quot;NavAlt-anchor u-b0&quot;]</value>
      <webElementGuid>8c989093-6b21-47a1-be90-3c0b779b7a87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_T53129E6C012_Col00']/nav/div/div[2]/a[2]</value>
      <webElementGuid>8c56762c-e04e-4282-bb41-eb0bb97846e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Desktop')]</value>
      <webElementGuid>ab4c0a06-f21c-4627-9436-5768ae61965b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web'])[2]/following::a[1]</value>
      <webElementGuid>ebbf22a7-6d50-42e8-8311-30cc91c9a901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demos'])[3]/following::a[2]</value>
      <webElementGuid>497d0c69-cd88-4789-b59e-2d98b4bee333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[2]/preceding::a[1]</value>
      <webElementGuid>b0c5ca55-c2a2-4e27-8829-b5327be2fd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporting &amp; QA'])[1]/preceding::a[2]</value>
      <webElementGuid>847245f3-2060-455e-84a3-5203c9b2c115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#desktop')]</value>
      <webElementGuid>880be613-4120-4e62-b2c9-2f4a6f966510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[2]/a[2]</value>
      <webElementGuid>1149a420-d493-4dda-b04a-5a36e582d29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#desktop' and (text() = 'Desktop' or . = 'Desktop')]</value>
      <webElementGuid>90860553-2a6d-487c-8370-c02331b070a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
