<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mobile</name>
   <tag></tag>
   <elementGuidId>25087bee-26df-4969-bbfc-2f2b3f43d295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_T53129E6C012_Col00']/nav/div/div[2]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc074e2c-20d4-480f-8ac2-6edac804506c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#mobile</value>
      <webElementGuid>253590a4-7c87-4395-823d-baf14b9a552c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavAlt-anchor u-b0</value>
      <webElementGuid>3bb1c482-fdcb-4049-9b18-7bf2ba5e543a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Mobile content</value>
      <webElementGuid>91172031-ac13-4891-891c-83a194fd4e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile</value>
      <webElementGuid>a0a86b4a-36c8-4a3d-8527-78b414bc15c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_T53129E6C012_Col00&quot;)/nav[@class=&quot;NavAlt NavAlt--blue u-bn u-tal u-b0 is-fixed&quot;]/div[@class=&quot;container&quot;]/div[2]/a[@class=&quot;NavAlt-anchor u-b0&quot;]</value>
      <webElementGuid>44050e53-5847-4889-a9fa-0015d383c28f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_T53129E6C012_Col00']/nav/div/div[2]/a[3]</value>
      <webElementGuid>0e177a92-1d12-4f26-a803-0a0e4f0d08e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mobile')]</value>
      <webElementGuid>7ab1d229-9aca-4a8b-9962-840e42e28daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desktop'])[2]/following::a[1]</value>
      <webElementGuid>5ba9207d-8647-4395-8fa9-0f0f9659ca87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web'])[2]/following::a[2]</value>
      <webElementGuid>1cf5fd44-e03f-4987-aa6a-4d32de3b1bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporting &amp; QA'])[1]/preceding::a[1]</value>
      <webElementGuid>b2863f14-54a8-4033-bd2a-01d381b2f358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conversational UI'])[1]/preceding::a[2]</value>
      <webElementGuid>ceec2f97-87ae-4485-98fd-e71ce8eae213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#mobile')]</value>
      <webElementGuid>455b970a-dc92-4e52-ab49-1a1d072f0529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[2]/a[3]</value>
      <webElementGuid>e11dcd79-867b-46c8-8aa0-a29ffaf97ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#mobile' and (text() = 'Mobile' or . = 'Mobile')]</value>
      <webElementGuid>6c9ade52-aae3-4c13-8ede-5b099683a094</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
