<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Webinars</name>
   <tag></tag>
   <elementGuidId>45684eca-c379-49de-a75b-9129a3632051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='telerik']/footer/div/div/div[2]/div/div[2]/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5e32bfc1-3830-4053-b114-abca03207ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/webinars</value>
      <webElementGuid>4f3aa85a-cb29-40af-b035-3cb49b91cdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TK-Footer-Link</value>
      <webElementGuid>a9d804de-1c6d-44e1-a0ce-18d1b824caf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Webinars</value>
      <webElementGuid>d9e0aa96-7616-42e9-a5a9-f13f32d2c44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telerik&quot;)/footer[@class=&quot;TK-Footer&quot;]/div[@class=&quot;TK-container&quot;]/div[@class=&quot;TK-row TK-No-Print&quot;]/div[@class=&quot;TK-col-16&quot;]/div[@class=&quot;TK-row&quot;]/div[@class=&quot;TK-col-6 TK--Footer-Desktop&quot;]/ul[@class=&quot;TK-Footer-List&quot;]/li[@class=&quot;TK-Footer-List-Item&quot;]/a[@class=&quot;TK-Footer-Link&quot;]</value>
      <webElementGuid>717dffc8-bb84-4f4e-9d7c-2fcd9f35b909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='telerik']/footer/div/div/div[2]/div/div[2]/ul/li[6]/a</value>
      <webElementGuid>24925810-db4a-48b3-a4f4-85a7293ecc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Webinars')]</value>
      <webElementGuid>e67c6c00-f8fd-4be8-922b-03bc549bf1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blogs'])[2]/following::a[1]</value>
      <webElementGuid>5e51ab9f-a80f-48e7-92e1-a8fc9f0ccb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forums'])[1]/following::a[2]</value>
      <webElementGuid>47269d05-48c2-4a29-911a-f18f56c06991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Professional Services'])[1]/preceding::a[1]</value>
      <webElementGuid>4e90675d-f3c0-4aa7-9e3e-4b9a4018a16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::a[2]</value>
      <webElementGuid>7be75a78-a6f5-43d2-af57-145362cfa19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Webinars']/parent::*</value>
      <webElementGuid>f05b6e60-2450-419d-a4d8-12fb557fd9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/webinars')])[3]</value>
      <webElementGuid>dd9ecbe1-7f66-47f8-a12d-5759529d31d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div[2]/div/div[2]/ul/li[6]/a</value>
      <webElementGuid>65ecaa1a-6a2e-4c76-a6b7-6c496be7efeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/webinars' and (text() = 'Webinars' or . = 'Webinars')]</value>
      <webElementGuid>36908493-cdbb-4d20-a74c-fe40bb39beaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
