<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Web</name>
   <tag></tag>
   <elementGuidId>c248e728-3268-49ca-8815-f60a5257d7c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_T53129E6C012_Col00']/nav/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.NavAlt-anchor.u-b0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c80ca2bb-e996-499a-86b9-93231e983ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#web</value>
      <webElementGuid>6ed8c1dd-892b-4b31-8f7d-c7d0ce8d7654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavAlt-anchor u-b0</value>
      <webElementGuid>550bfa83-e5b9-4169-92d0-1d37eedcf63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Web content</value>
      <webElementGuid>bfa1a8bc-7e83-44fe-86e6-fbb0d56fb7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Web</value>
      <webElementGuid>dc94990b-0cd1-41be-9d59-be3d512c7ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_T53129E6C012_Col00&quot;)/nav[@class=&quot;NavAlt NavAlt--blue u-bn u-tal u-b0&quot;]/div[@class=&quot;container&quot;]/div[2]/a[@class=&quot;NavAlt-anchor u-b0&quot;]</value>
      <webElementGuid>71d0ba80-7d1c-4a82-8732-a727338436eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_T53129E6C012_Col00']/nav/div/div[2]/a</value>
      <webElementGuid>f2fa9caa-3859-4cb9-8e96-ddf4ab367f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Web')]</value>
      <webElementGuid>37a82588-9c9f-4924-be4d-dd584612a546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demos'])[3]/following::a[1]</value>
      <webElementGuid>3fbf45d1-6be6-4cf5-9104-6ab87032fa68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demos'])[2]/following::a[1]</value>
      <webElementGuid>4947b458-676b-4b1b-ac27-7cfdc9f2e786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desktop'])[2]/preceding::a[1]</value>
      <webElementGuid>8da02561-53ab-489f-815d-3aefc4f7d328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[2]/preceding::a[2]</value>
      <webElementGuid>74b40703-1a16-4174-bdbf-95e589a1d986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#web')]</value>
      <webElementGuid>a4d73914-d69e-44d6-96bd-8f8690b9fc9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[2]/a</value>
      <webElementGuid>dfc70cb4-9ce6-4401-92a4-b7843084e0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#web' and (text() = 'Web' or . = 'Web')]</value>
      <webElementGuid>eb39a7ed-c0b3-4e8c-877a-34e9db18fbb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
