<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_State or Province_stateProvince</name>
   <tag></tag>
   <elementGuidId>9b9ef54d-bbf6-488d-8c3b-af266d31f873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stateProvince</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stateProvince']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88600aac-b36d-4106-b88a-8fdad7e70ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stateProvince</value>
      <webElementGuid>53be8ed7-b15b-4e86-bbf9-149de33ce7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>State or Province</value>
      <webElementGuid>17489bf8-d3eb-4a21-96cf-77863bbe6916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stateProvince&quot;)</value>
      <webElementGuid>0e78f5e5-397e-49a6-b317-1d3b4046277e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stateProvince']</value>
      <webElementGuid>aa924e6d-f750-40a1-97f9-e3b4205c3bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-contact']/p[6]/input[2]</value>
      <webElementGuid>ebf482d9-cf83-45d2-9269-e228bfb73c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/input[2]</value>
      <webElementGuid>1b2925ed-f2ed-4294-a727-fe3c0d598e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'stateProvince' and @placeholder = 'State or Province']</value>
      <webElementGuid>b2190d98-2810-47cb-8de7-a653738458d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
