<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address 1_street1</name>
   <tag></tag>
   <elementGuidId>dc665d35-53b2-429c-a269-0de6e961a71d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#street1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='street1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6374529b-ff95-4f53-9566-942c256c3429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>street1</value>
      <webElementGuid>28dc52e0-f33e-48c6-98a9-3a625168faaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address 1</value>
      <webElementGuid>843b1227-e200-461d-aa43-4bc279e86801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;street1&quot;)</value>
      <webElementGuid>fe29c26c-6f84-49ea-9045-fb5dd2beb618</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='street1']</value>
      <webElementGuid>1a18b00a-9b7e-40bf-9f2f-0baccc5c94be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-contact']/p[4]/input</value>
      <webElementGuid>c606642f-3524-4e55-938d-64e004372a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/input</value>
      <webElementGuid>7a649e2e-12b0-4ee0-ae14-9fde9e74bf5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'street1' and @placeholder = 'Address 1']</value>
      <webElementGuid>a05a420d-2ad7-4912-bd93-148d4f9b16c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
