<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address 2_street2</name>
   <tag></tag>
   <elementGuidId>cc01c3bb-1bf5-4c50-9cff-c3e47fe0461a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#street2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='street2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c89d006-953c-41bf-9dcd-cf668b992983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>street2</value>
      <webElementGuid>ffd1cc6a-2fcd-4553-9ddc-36b9879b935d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address 2</value>
      <webElementGuid>990099bb-3167-4bf7-9e5f-62638fb64aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;street2&quot;)</value>
      <webElementGuid>4cf267c9-4806-4f73-bc97-9b5afb08dbdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='street2']</value>
      <webElementGuid>862f29f8-67d9-4d13-98b7-5056c8a9f692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-contact']/p[5]/input</value>
      <webElementGuid>292da802-458d-480e-b883-3b7f5e2d0886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input</value>
      <webElementGuid>3d788721-9148-47e5-8a88-b2cba33578de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'street2' and @placeholder = 'Address 2']</value>
      <webElementGuid>ff849bea-8dfa-4896-afe5-8f5b8371d45f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
