<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add a New Contact</name>
   <tag></tag>
   <elementGuidId>f0db918c-1d46-48ab-b151-87198f40ee6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-contact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-contact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3d7b510-1d0e-4df6-9ac1-1bd5bfc13217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-contact</value>
      <webElementGuid>b81d7818-efc1-42e5-ae68-fc2e7db13820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='/addContact'</value>
      <webElementGuid>f2765a11-9b38-48bc-977b-6df45c7d5012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add a New Contact</value>
      <webElementGuid>311a6bde-c9da-478f-a1cf-f79689f4e064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-contact&quot;)</value>
      <webElementGuid>fbcfb450-1b16-4287-8f8c-7572bcdab9ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-contact']</value>
      <webElementGuid>ce4f1fa3-0627-49c3-a14b-21bbd3fe0f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::button[1]</value>
      <webElementGuid>ef69d786-4de0-4cfb-b5b9-1ee406653713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact List'])[1]/following::button[2]</value>
      <webElementGuid>fd016dbe-42c0-4959-a79c-5dbd4f34d5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::button[1]</value>
      <webElementGuid>ff943836-a494-4e13-b792-888230086c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birthdate'])[1]/preceding::button[1]</value>
      <webElementGuid>550a698f-9507-43bb-9301-e05508fa2b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add a New Contact']/parent::*</value>
      <webElementGuid>a40896fe-618a-4c62-b00b-c381a40e8778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/button</value>
      <webElementGuid>ad7d0a60-8059-4f83-9788-8667ecc2ae34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'add-contact' and (text() = 'Add a New Contact' or . = 'Add a New Contact')]</value>
      <webElementGuid>4908fed8-4988-4797-a044-289556871ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
