<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Products</name>
   <tag></tag>
   <elementGuidId>bf0c36d2-6473-497d-ac15-4e030c9923d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[11]/div/div/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-1sf3xto > span.MuiTypography-root.MuiTypography-label.css-bx6rut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d6f903d9-961b-41fc-8ee8-ef0ab319a133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-label css-bx6rut</value>
      <webElementGuid>d219f435-7a34-473f-8e3e-a62bb481d7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>b15a95b9-7176-49e4-a9bd-9dc7f8f095cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-70ca4w&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg css-ljahw8&quot;]/div[@class=&quot;css-qbaz9b&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation1 MuiAccordion-root css-1r0gzaa&quot;]/div[@class=&quot;MuiButtonBase-root MuiAccordionSummary-root css-kir3m8&quot;]/div[@class=&quot;MuiAccordionSummary-content css-1n11r91&quot;]/div[@class=&quot;MuiBox-root css-1sf3xto&quot;]/span[@class=&quot;MuiTypography-root MuiTypography-label css-bx6rut&quot;]</value>
      <webElementGuid>ff0a7bfd-755e-40de-b92c-fd4be2eede59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[11]/div/div/div/div/div/div/span</value>
      <webElementGuid>ae60e554-bc34-4ac3-817e-ed0fe6bd0eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn More'])[3]/following::span[1]</value>
      <webElementGuid>f4d2b039-b1b2-4cdb-b22f-c1919a51e67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clair Byrd Joins Sauce Labs as Chief Marketing Officer'])[1]/following::span[2]</value>
      <webElementGuid>be5cf396-bad1-4baa-9e1c-678d054db880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sauce DevOps Test Toolchain'])[1]/preceding::span[2]</value>
      <webElementGuid>48c80783-3fe8-49ee-9475-40248c302bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sauce Cross-Browser'])[3]/preceding::span[3]</value>
      <webElementGuid>e881e265-ae85-45f1-8b07-57b5f9afb27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div/span</value>
      <webElementGuid>36356052-b7c2-422c-8c3d-9e6771b22eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Products' or . = 'Products')]</value>
      <webElementGuid>18e40365-3af2-4f3d-8982-48378737ca43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
