<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verify Text</name>
   <tag></tag>
   <elementGuidId>7a185ce8-c9be-4941-87c6-4022c2809554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='overview']/div/div[3]/div[3]/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b81a728a-99a0-4be0-a3f3-62ab346b7d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/verifytext</value>
      <webElementGuid>485d824b-6986-43c6-87c3-2657503de1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify Text</value>
      <webElementGuid>ec897388-c717-402e-b8b4-038eb566765d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overview&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm&quot;]/h3[1]/a[1]</value>
      <webElementGuid>1b31b822-869b-4879-b890-3394c7e51c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='overview']/div/div[3]/div[3]/h3/a</value>
      <webElementGuid>846946e6-ba80-4ab2-8cfa-1ae7882d0a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verify Text')]</value>
      <webElementGuid>6ff2161e-99c7-4963-a7de-bed395dde642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Table'])[1]/following::a[1]</value>
      <webElementGuid>710c3c92-5eb2-4fe5-b3a6-2c0a122621cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scrollbars'])[1]/following::a[2]</value>
      <webElementGuid>03be122c-d5f0-4b72-b5b4-092050a9331b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Progress Bar'])[1]/preceding::a[1]</value>
      <webElementGuid>8659a1dd-8493-4d04-ac33-4108801d173e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibility'])[1]/preceding::a[2]</value>
      <webElementGuid>bd7ad98c-dc75-44d7-b643-26b66ed09099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verify Text']/parent::*</value>
      <webElementGuid>983f5aac-37b8-4d69-ad51-53df5de88709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/verifytext')]</value>
      <webElementGuid>0039c320-79d1-4c04-80c9-621a4feabe14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/h3/a</value>
      <webElementGuid>a2f79538-c67f-4cad-9a01-a44b9247d9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/verifytext' and (text() = 'Verify Text' or . = 'Verify Text')]</value>
      <webElementGuid>7850d2bc-d405-4cf1-a2b6-e12b1dec78ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
