<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blog</name>
   <tag></tag>
   <elementGuidId>88c4c9e9-1dd0-44a4-90fc-6584cb281066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.et_pb_menu_page_id-213448.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-214031 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-home-page-menu']/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1622ae41-067d-42de-987f-207a471025ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ultimateqa.com/blog/</value>
      <webElementGuid>c4f51a8f-8f3b-48c3-83c8-e6cc24d3bf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>78932f91-8672-42b9-a96b-d34b4b06168c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-home-page-menu&quot;)/li[@class=&quot;et_pb_menu_page_id-213448 menu-item menu-item-type-post_type menu-item-object-page menu-item-214031&quot;]/a[1]</value>
      <webElementGuid>62641076-cae2-4456-b631-30ddde71a039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-home-page-menu']/li[5]/a</value>
      <webElementGuid>5bddee91-2d76-49c5-a77c-d2ed15c1c8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Blog')]</value>
      <webElementGuid>3afb6125-297c-4622-9fa0-ccb69b7fe663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success Stories'])[1]/following::a[1]</value>
      <webElementGuid>686ef9e8-230d-44a6-8301-f9dc4cebe747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Exercises'])[1]/following::a[2]</value>
      <webElementGuid>b3755190-e1b0-4cc2-9168-0920fa73fdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::a[1]</value>
      <webElementGuid>a6cacd21-64ab-4200-acf3-65f079fb0289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[2]</value>
      <webElementGuid>d2976434-194c-4e7f-b899-bfc54dba9673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blog']/parent::*</value>
      <webElementGuid>e3ed2219-256c-43ac-a799-1f8f9ace1539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ultimateqa.com/blog/')]</value>
      <webElementGuid>e6a81a99-1485-473e-8636-2e3e14c0bbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>68168a11-66de-4792-ae50-a1170c70a413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ultimateqa.com/blog/' and (text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>b5230a7b-0b79-4b2c-a9f9-d01ec5fd1a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
