<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Learning</name>
   <tag></tag>
   <elementGuidId>8fb379c6-1a56-4a9d-9cee-d12d6d16777e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.et_pb_menu_page_id-217437.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-has-children.menu-item-217440 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-home-page-menu']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b898877-5c40-4565-b0fd-78107a903a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ultimateqa.com/learning/</value>
      <webElementGuid>428be373-cbc6-4610-a498-9eb44f7c103b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learning</value>
      <webElementGuid>ca974ebf-5b05-471a-8927-eacfc0451e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-home-page-menu&quot;)/li[@class=&quot;et_pb_menu_page_id-217437 menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-217440&quot;]/a[1]</value>
      <webElementGuid>d9bfef77-2d07-4d09-be39-bb8060cfd440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-home-page-menu']/li[3]/a</value>
      <webElementGuid>5000ea15-3c66-4308-9d49-66d69dcc2d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Learning')]</value>
      <webElementGuid>e984a06b-83e1-4ab9-9e63-00984e607332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java SDET Academy'])[1]/following::a[1]</value>
      <webElementGuid>a413a322-c240-4fce-924a-9ef65f999ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Professional Services'])[1]/following::a[2]</value>
      <webElementGuid>ac9731ef-8caf-47d0-b007-46d363086366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Courses'])[1]/preceding::a[1]</value>
      <webElementGuid>5466208d-bbe3-42a0-8474-695cde28b588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Java'])[1]/preceding::a[2]</value>
      <webElementGuid>764ca769-5478-4362-b5e3-5d5e51a95c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Learning']/parent::*</value>
      <webElementGuid>1af9786d-a95e-48f2-880f-b0a2128ad91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ultimateqa.com/learning/')]</value>
      <webElementGuid>5d06fe0f-997e-4f64-b1b1-d1c9829367b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>810eec5d-26c8-41f0-b2b2-e0e95baf27a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ultimateqa.com/learning/' and (text() = 'Learning' or . = 'Learning')]</value>
      <webElementGuid>ca666048-a13a-4536-9653-e5b9fe5a4b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
